### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by edboffical** [bytedance/AgentSmith-HIDS#18]
str8@str8 LKM]$ make clean && make
make -C /lib/modules/5.10.23-1-MANJARO/build M=/home/str8/Data/AgentSmith-HIDS/driver/LKM clean
make[1]: Entering directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
/home/str8/Data/AgentSmith-HIDS/driver/LKM/Makefile:23: 
make[1]: Leaving directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
make -C /lib/modules/5.10.23-1-MANJARO/build M=/home/str8/Data/AgentSmith-HIDS/driver/LKM modules
make[1]: Entering directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
/home/str8/Data/AgentSmith-HIDS/driver/LKM/Makefile:23: 
  CC [M]  /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/init.o
  CC [M]  /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/kprobe.o
  CC [M]  /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.o
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function 'is_trace_empty':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:136:40: error: passing argument 1 of 'ring_buffer_empty_cpu' from incompatible pointer type [-Werror=incompatible-pointer-types]
  136 |         if (!ring_buffer_empty_cpu(iter->buffer, cpu))
      |                                    ~~~~^~~~~~~~
      |                                        |
      |                                        struct ring_buffer *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/../include/trace.h:7,
                 from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:12:
./include/linux/ring_buffer.h:162:49: note: expected 'struct trace_buffer *' but argument is of type 'struct ring_buffer *'
  162 | bool ring_buffer_empty_cpu(struct trace_buffer *buffer, int cpu);
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function 'peek_next_entry':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:179:34: error: passing argument 1 of 'ring_buffer_peek' from incompatible pointer type [-Werror=incompatible-pointer-types]
  179 |     event = ring_buffer_peek(iter->buffer, cpu, ts, lost_events);
      |                              ~~~~^~~~~~~~
      |                                  |
      |                                  struct ring_buffer *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/../include/trace.h:7,
                 from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:12:
./include/linux/ring_buffer.h:124:39: note: expected 'struct trace_buffer *' but argument is of type 'struct ring_buffer *'
  124 | ring_buffer_peek(struct trace_buffer *buffer, int cpu, u64 *ts,
      |                  ~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function '__find_next_entry':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:202:35: error: passing argument 1 of 'ring_buffer_empty_cpu' from incompatible pointer type [-Werror=incompatible-pointer-types]
  202 |         if (ring_buffer_empty_cpu(buffer, cpu))
      |                                   ^~~~~~
      |                                   |
      |                                   struct ring_buffer *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/../include/trace.h:7,
                 from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:12:
./include/linux/ring_buffer.h:162:49: note: expected 'struct trace_buffer *' but argument is of type 'struct ring_buffer *'
  162 | bool ring_buffer_empty_cpu(struct trace_buffer *buffer, int cpu);
      |                            ~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function 'trace_read_pipe':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:331:33: error: passing argument 1 of 'ring_buffer_consume' from incompatible pointer type [-Werror=incompatible-pointer-types]
  331 |         ring_buffer_consume(iter->buffer, iter->cpu, &iter->ts, &iter->lost_events);
      |                             ~~~~^~~~~~~~
      |                                 |
      |                                 struct ring_buffer *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/../include/trace.h:7,
                 from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:12:
./include/linux/ring_buffer.h:127:42: note: expected 'struct trace_buffer *' but argument is of type 'struct ring_buffer *'
  127 | ring_buffer_consume(struct trace_buffer *buffer, int cpu, u64 *ts,
      |                     ~~~~~~~~~~~~~~~~~~~~~^~~~~~
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function 'print_event_init':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:411:17: error: assignment to 'struct ring_buffer *' from incompatible pointer type 'struct trace_buffer *' [-Werror=incompatible-pointer-types]
  411 |     ring_buffer = ring_buffer_alloc(RB_BUFFER_SIZE, RB_FL_OVERWRITE);
      |                 ^
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:420:27: error: passing argument 4 of 'proc_create_data' from incompatible pointer type [-Werror=incompatible-pointer-types]
  420 |                           &trace_pipe_fops, ring_buffer))
      |                           ^~~~~~~~~~~~~~~~
      |                           |
      |                           const struct file_operations *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:9:
./include/linux/proc_fs.h:106:13: note: expected 'const struct proc_ops *' but argument is of type 'const struct file_operations *'
  106 |             const struct proc_ops *,
      |             ^~~~~~~~~~~~~~~~~~~~~~~
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c: In function 'print_event_exit':
/home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:449:22: error: passing argument 1 of 'ring_buffer_free' from incompatible pointer type [-Werror=incompatible-pointer-types]
  449 |     ring_buffer_free(ring_buffer);
      |                      ^~~~~~~~~~~
      |                      |
      |                      struct ring_buffer *
In file included from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/../include/trace.h:7,
                 from /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.c:12:
./include/linux/ring_buffer.h:107:44: note: expected 'struct trace_buffer *' but argument is of type 'struct ring_buffer *'
  107 | void ring_buffer_free(struct trace_buffer *buffer);
      |                       ~~~~~~~~~~~~~~~~~~~~~^~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /home/str8/Data/AgentSmith-HIDS/driver/LKM/src/trace.o] Error 1
make[1]: *** [Makefile:1801: /home/str8/Data/AgentSmith-HIDS/driver/LKM] Error 2
make[1]: Leaving directory '/usr/lib/modules/5.10.23-1-MANJARO/build'
make: *** [Makefile:32: all] Error 2

**Comment by EBWi11** [comment]
目前还不支持5.10，目前支持的kernel version范围是3.10 - 5.4.下个版本会到2.6.32 - 5.11
