### ISSUE TITLE
More descriptive commit message.

### ISSUE THREAD

**Issue by Escapingbug** [bytedance/AgentSmith-HIDS#21]
Currently the project's commit message is kind of confusing. Many "update something" commit messages are used.
![image](https://user-images.githubusercontent.com/19388242/112090632-e36c9500-8bce-11eb-9c66-779613092140.png)

If it is possible, could we adopt some sort of specification for commit messages? Like, one that provided [here](https://www.conventionalcommits.org/en/v1.0.0/)? At least from now on?

I have fired two pull request on this project, if we are gonna adopt such a convention, I'm totally ok to refine my commit messages. :)

**Comment by EBWi11** [comment]
so sorry about that,many "update something"  was fix some bug and tiny fix.I will pull as our PULL_REQUEST_TEMPLATE.md agreed in the future.
and thx your pull requests :)
