### ISSUE TITLE
driver插件编译有报错

### ISSUE THREAD

**Issue by shen771** [bytedance/AgentSmith-HIDS#22]
root@st-arch-sec-tool-1 (14:30:24) driver # pwd
/tmp/AgentSmith-HIDS-main/agent/driver
root@st-arch-sec-tool-1 (14:37:41) driver # ls
build.rs  Cargo.toml  LICENSE  Makefile  README.md  README-zh_CN.md  src  template.toml

root@st-arch-sec-tool-1 (14:39:55) .cargo # pwd     //cargo build 等待并巨慢的问题，改了源
/root/.cargo
root@st-arch-sec-tool-1 (14:39:51) .cargo # cat config
[source.crates-io]
registry = "https://github.com/rust-lang/crates.io-index"
replace-with = 'ustc'
[source.ustc]
registry = "git://mirrors.ustc.edu.cn/crates.io-index"

root@st-arch-sec-tool-1 (14:30:09) driver # make build
cargo build --release
    Updating `git://mirrors.ustc.edu.cn/crates.io-index` index
error: failed to get `flexi_logger` as a dependency of package `plugin_builder v0.1.0 (/tmp/AgentSmith-HIDS-main/agent/support/rust/plugin_builder)`
    ... which is depended on by `driver v0.1.0 (/tmp/AgentSmith-HIDS-main/agent/driver)`

Caused by:
  failed to load source for dependency `flexi_logger`

Caused by:
  Unable to update /tmp/AgentSmith-HIDS-main/agent/support/rust/flexi_logger

Caused by:
  failed to read `/tmp/AgentSmith-HIDS-main/agent/support/rust/flexi_logger/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
make: *** [build] Error 101

**Comment by ZhangLei-cn** [comment]
尝试git clone --recursive https://github.com/bytedance/AgentSmith-HIDS

**Comment by ZhangLei-cn** [comment]
或者git submodule update --init

**Comment by shen771** [comment]
不好意思再三打扰，还要麻烦下，

root@st-arch-sec-tool-1 (14:25:06) ~ # git clone --recursive https://github.com/bytedance/AgentSmith-HIDS
Cloning into 'AgentSmith-HIDS'...
remote: Enumerating objects: 193, done.
remote: Counting objects: 100% (193/193), done.
remote: Compressing objects: 100% (139/139), done.
remote: Total 740 (delta 120), reused 105 (delta 54), pack-reused 547
Receiving objects: 100% (740/740), 3.64 MiB | 451.00 KiB/s, done.
Resolving deltas: 100% (358/358), done.
Submodule 'agent/support/rust/flexi_logger' (git@github.com:bytedance/flexi_logger.git) registered for path 'agent/support/rust/flexi_logger'
Cloning into 'agent/support/rust/flexi_logger'...
The authenticity of host 'github.com (13.250.177.223)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,13.250.177.223' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:bytedance/flexi_logger.git' into submodule path 'agent/support/rust/flexi_logger' failed

**Comment by ZhangLei-cn** [comment]
如果遇到上述错误，请检查自己的GitHub身份配置：

**Comment by WinFoot** [comment]
另一种简单粗暴的办法：
cd ./AgentSmith-HIDS/agent/support/rust
git clone https://github.com/bytedance/flexi_logger.git

**Comment by ZhangLei-cn** [comment]
> 另一种简单粗暴的办法：
> cd ./AgentSmith-HIDS/agent/support/rust
> git clone https://github.com/bytedance/flexi_logger.git

yes,thx.
